### ISSUE TITLE
Error on send request to DogeDaemon

### ISSUE THREAD

**Issue by just-an-dev** [just-an-dev/sodogetip#28]
Stack trace :

```
Traceback (most recent call last):
  File "dogetipper.py", line 70, in main
    bot_command.balance_user(self.rpc_main, msg)
  File "/usr/src/app/bot_command.py", line 28, in balance_user
    balance = crypto.get_user_balance(rpc, msg.author.name)
  File "/usr/src/app/crypto.py", line 15, in get_user_balance
    list_unspent = rpc.listunspent(1, 99999999999, [address])
  File "/usr/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 136, in __call__
    'Content-type': 'application/json'})
  File "/usr/local/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1076, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python2.7/httplib.py", line 924, in putrequest
    raise CannotSendRequest()
CannotSendRequest
```

**Comment by just-an-dev** [comment]
it happened after a timeout: timed out


```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "dogetipper.py", line 115, in anti_spamming_tx
    list_tx = self.rpc_antispam.listunspent(1, 99999999999, [address])
  File "/usr/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 139, in __call__
    response = self._get_response()
  File "/usr/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 179, in _get_response
    http_response = self.__conn.getresponse()
  File "/usr/local/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
```
