### ISSUE TITLE
limit entry on history

### ISSUE THREAD

**Issue by just-an-dev** [just-an-dev/sodogetip#65]
maybe to 30 last entry

**Comment by just-an-dev** [comment]
```
Traceback (most recent call last):
  File "/usr/src/app/dogetipper.py", line 68, in main
    bot_command.history_user(msg)
  File "/usr/src/app/bot_command.py", line 285, in history_user
    msg.reply(Template(lang.message_history + history_table + lang.message_footer).render(username=msg.author.name))
  File "/usr/local/lib/python2.7/site-packages/praw/models/reddit/mixins/replyable.py", line 16, in reply
    return self._reddit.post(API_PATH['comment'], data=data)[0]
  File "/usr/local/lib/python2.7/site-packages/praw/reddit.py", line 411, in post
    return self._objector.objectify(data)
  File "/usr/local/lib/python2.7/site-packages/praw/objector.py", line 122, in objectify
    raise APIException(*errors[0])
APIException: TOO_LONG: 'this is too long (max: 10000)' on field 'text'
```
